import express from "express";
import nodemailer from "nodemailer";
import validator from "validator";
import xssFilters from "xss-filters";

const app = express();

app.use(express.json());

app.post("/", (req, res) => {
  const attributes = ["prihod", "odhod", "odrasli", "otroci", "email"]; // Our five form fields, all required

  //   // Map each attribute name to the validated and sanitized equivalent (false if validation failed)
  //   const sanitizedAttributes = attributes.map((n) =>
  //     validateAndSanitize(n, req.body[n]),
  //   );

  //   // True if some of the attributes new values are false -> validation failed
  //   const someInvalid = sanitizedAttributes.some((r) => !r);

  //   if (someInvalid) {
  //     // Throw a 422 with a neat error message if validation failed
  //     return res.status(422).json({ error: "Ugh.. That looks unprocessable!" });
  //   }
  sendMail();
  res.status(200).json({ message: "OH YEAH" });
});

// const validateAndSanitize = (key, value) => {
//   const rejectFunctions = new Map([
//     // ["prihod", (v) => v.length < 1],
//     // ["odhod", (v) => v.length < 0],
//     // ["odrasli", (v) => v.length < 1],
//     // ["otroci", (v) => v.length < 0],
//     ["email", (v) => !validator.isEmail(v)],
//   ]);
//   // If map has key and function returns false, return sanitized input. Else, return false
//   return (
//     rejectFunctions.has(key) &&
//     !rejectFunctions.get(key)(value) &&
//     xssFilters.inHTMLData(value)
//   );
// };

const sendMail = (prihod, odhod, odrasli, otroci, email) => {
  const transporter = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "94bba965a5d6f2", // generated by Mailtrap
      pass: "285f9a0705d251", // generated by Mailtrap
    },
  });
  transporter.sendMail({
    from: email,
    to: "krajnc.mare@gmail.com",
    subject: "Povpraševanje - najem posestva",
    text: "prihod: $prihod",
    odhod,
    odrasli,
    otroci,
    email,
  });
};

export default {
  path: "/api/contact",
  handler: app,
};
